### ISSUE TITLE
Rename OrthogonalPolynomialsAlgebraicCurves.jl

### ISSUE THREAD

**Issue by dlfivefifty** [dlfivefifty/OrthogonalPolynomialsAlgebraicCurves.jl#1]
I want to make this a package, to help prevent making breaking changes. First step is to rename it

**Comment by dlfivefifty** [comment]
Actually can you just add me as an admin? I want to also enable CI

**Comment by MarcoFasondini** [comment]
Sure, it seems I don't have the option to let both of us have admin access, so I'll transfer the repos to you

**Comment by dlfivefifty** [comment]
Maybe better to transfer to JuliaApproximation?
